AWSTemplateFormatVersion: "2010-09-09"

Description: This template creates a EC2 Instance with ubuntu image based on selected options.

Metadata:
  AWS::Cloudformation::Interface:
    ParameterGroups:
      - Label:
          default: "Instance Settings"
        Parameters:
          - InstanceName
          - InstanceType
          - KeyName
          - SecurityGroup
          - VolumeSize
          - VolumeType

Parameters:
  InstanceName:
    Description: Type the instance name
    Type: String
  
  InstanceType:
    Description: Choose the instance type
    Type: String
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
    
  KeyName:
    Description: Select the key pair
    Type: AWS::EC2::KeyPair::KeyName
  
  SecurityGroup:
    Description: Select the Security Group
    Type: AWS::EC2::SecurityGroup::Id
  
  VolumeSize:
    Description: Volume Size(in gigabytes)
    Type: Number
  
  VolumeType:
    Description: Select the volume type
    Type: String
    AllowedValues:
         - gp2
         - gp3
  
Mappings:
     RegionMapAMI:
      us-east-1:
        AMI: ami-053b0d53c279acc90
      us-east-2:
        AMI: ami-024e6efaf93d85776
      sa-east-1:
        AMI: ami-0af6e9042ea5a4e3e


Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: !FindInMap
        - RegionMapAMI
        - !Ref AWS::Region
        - AMI
      Tags:
        - Key: "Name"
          Value: !Ref InstanceName
      SecurityGroupIds:
       - !Ref SecurityGroup
      BlockDeviceMappings:
       - DeviceName: /dev/sda1 # this device name works only for ubuntu AMI's, you should search for other AMI's device names to avoid problems with your storage
         Ebs:
           VolumeType: !Ref VolumeType
           VolumeSize: !Ref VolumeSize
           DeleteOnTermination: true
           Encrypted: false

Outputs:
  Instance:
    Description: Instance ID
    Value: !Ref EC2Instance
  AvailabilityZone:
    Description: Availability Zone
    Value: !GetAtt EC2Instance.AvailabilityZone
  PrivateIp:
    Description: Private IP
    Value: !GetAtt EC2Instance.PrivateIp
  PublicIp:
    Description: Public IP
    Value: !GetAtt EC2Instance.PublicIp
  